production:
  address: "smtp.mailgun.org"
  port: "587"
  domain: "gmail.com"
  authentication: "plain"
  user_name: <%= ENV["EMAIL_USERNAME"] %>
  password: <%= ENV["EMAIL_PASSWORD"] %>
  enable_starttls_auto: true